services:
  - type: web
    name: zus-chatbot-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/backend.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: BASE_URL
        sync: false

    healthCheckPath: /health
